package org.ditio.backend.Entities;

import jakarta.persistence.*;

import java.util.UUID;
import java.time.LocalDateTime;

/* ***Til DB_migration ***
CREATE TABLE IF NOT EXISTS event [
    event_id UUID PRIMARY KEY DEFAULT uuidv7(),

    title TEXT NOT NULL,
    description TEXT,

    start_time TIMESTAMP NOT NULL;
    end_time TIMESTAMP,

    location TEXT,

    max_attendees INTEGER,
    is_published BOOLEAN, ???

 */

@Entity
@Table(name = "event")
public class Event {

    @Id
    @GeneratedValue
    private UUID eventId; // UUIDv7 generated by DB, Spring will handle it

    @Column(nullable = false)
    private String title;

    @Column(length = 2000)
    private String description;

    @Column(nullable = false)
    private LocalDateTime startTime;

    private LocalDateTime endTime;

    private String location;

    private Integer maxAttendees;

    private boolean isPublished;

    //Constructors
    public Event() {}

    public Event(UUID eventId, String title, String description, LocalDateTime startTime, LocalDateTime endTime, String location, Integer maxAttendees, boolean isPublished) {
        this.eventId = eventId;
        this.title = title;
        this.description = description;
        this.startTime = startTime;
        this.endTime = endTime;
        this.location = location;
        this.maxAttendees = maxAttendees;
        this.isPublished = isPublished;
    }

    //Getters & setters
    public UUID getEventId() {return eventId;}

    public String getTitle() {return title;}
    public void setTitle(String title) {this.title = title;}

    public String getDescription() {return description;}
    public void setDescription(String description) {this.description = description;}

    public LocalDateTime getStartTime() {return startTime;}
    public void setStartTime(LocalDateTime startTime) {this.startTime = startTime;}

    public LocalDateTime getEndTime() {return endTime;}
    public void setEndTime(LocalDateTime endTime) {this.endTime = endTime;}

    public String getLocation() {return location;}
    public void setLocation(String location) {this.location = location;}

    public Integer getMaxAttendees() {return maxAttendees;}
    public void setMaxAttendees(Integer maxAttendees) {this.maxAttendees = maxAttendees;}

    public boolean getIsPublished() {return isPublished;}
    public void setIsPublished(boolean  isPublished) {this.isPublished = isPublished;}

}
