package org.ditio.backend.Entities;

import jakarta.persistence.*;
import java.util.UUID;

@Entity
@Table(name = "item")
public class Item {

    @Id
    @GeneratedValue
    private UUID id; // UUIDv7 generated by DB, Spring will handle it

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private int quantity = 0;

    @Column(nullable = false)
    private String origin; 


    // Constructors
    public Item() {}

    public Item(String name, int quantity, String origin) {
        this.name = name;
        this.quantity = quantity;
        this.origin = origin;
    }

    // Getters & Setters
    public UUID getId() { return id; }
    public void setId(UUID id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public int getQuantity() { return quantity; }
    public void setQuantity(int quantity) { this.quantity = quantity; }

    public String getOrigin() {return origin;}
    public void setOrigin(String origin) {this.origin = origin; }

}