
   

package org.ditio.backend.Entities;

import jakarta.persistence.*;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonProperty;

@Entity
@Table(name = "testAtt")
public class TestAtt {

    @Id
    @GeneratedValue
    private UUID att_list_id; // UUIDv7 generated by DB, Spring will handle it

    @Column(nullable = false)
    private int event_id;

    @Column(nullable = false)
    private String userIdString;

    @Column(nullable = false) //false inntil true
    private boolean att_status; 

    // Constructors
    public TestAtt() {}

    public TestAtt(UUID att_list_id, int event_id, String userIdString, boolean att_status) {
        this.att_list_id = att_list_id;
        this.event_id = event_id;
        this.userIdString = userIdString;
        this.att_status = att_status;
    }

    // Getters & Setters
    public UUID getAtt_list_id() { return att_list_id; }
    public void setAtt_list_id(UUID att_list_id) { this.att_list_id = att_list_id; }

    public int getEvent_id() { return event_id; }
    public void setEvent_id(int event_id) { this.event_id = event_id; }

    public String getUserIdString() { return userIdString; }
    public void setUserIdString(String userIdString) { this.userIdString = userIdString; }

    public boolean getAtt_status() {return att_status;}
    public void setAtt_status(boolean att_status) {this.att_status = att_status; }

}