spring.config.import=optional:file:.env[.properties]

spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL} 

spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info, flyway
management.endpoint.health.show-details=always
logging.level.org.flywaydb=INFO
# application.properties (midlertidig i dev)
logging.level.org.hibernate.SQL=DEBUG
# For Spring Boot 3 / Hibernate 6:
logging.level.org.hibernate.orm.jdbc.bind=TRACE


spring.profiles.active=${DEV_profile}
otp.secret=${OTP_CONFIG}
otp.secret.isBase32=${OTP_CONFIG_STATUS}
